# 
# Report generation script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
if {$argv == "synth_design"} {
  set retval [open_checkpoint top_demo.dcp]
  if { $retval == "checkpoint_top_demo" } {
  create_report "synth_1_synth_report_timing_0" "report_timing -file synth_report_timing_0.rpt -rpx synth_report_timing_0.rpx"
  
  close_design
  }
}
